### ISSUE TITLE
[Request] 10 years support on flatpak stable PPA for Ubuntu LTS versions 

### ISSUE THREAD

**Issue by MikeNavy** [flatpak/ppa-flatpak#10]
Hi,
On January 2023, Canonical has offered the possibility to each user to subscribe for free to Ubuntu Pro services (with a token valid for up to 5 computers per user).
With Ubuntu Pro, maintenance is available for 10 years instead of 5, for Ubuntu 16.04 LTS, 18.04 LTS, 20.04 LTS and 22.04 LTS. This pushes the end of life of these versions up to 2026-04-23 for 16.04 LTS, up to 2028-04-26 for 18.04 LTS, up to 2030-04-23 for 20.04 LTS, up to 2032-04-21 for 22.04 LTS.
Today, flatpak stable PPA, https://launchpad.net/~flatpak/+archive/ubuntu/stable, offers support for the 5 years duration of an LTS version without Ubuntu Pro enabled:

"Packages in this PPA are built for LTS branches of Ubuntu, currently
22.04 'jammy', 20.04 'focal' and 18.04 'bionic'. The newest LTS branch is treated as the highest priority for updates.
Packages for Ubuntu 16.04 'xenial' are no longer updated. Branches that have reached EOL for non-subscription-based updates are likely to stop receiving updates, or be removed from this PPA, when backports to those branches become too difficult."

My request is simple: update flatpak stable PPA during 10 years, for each LTS branch, up to the end of Ubuntu Pro support.

Regards,

MN

**Comment by smcv** [comment]
> My request is simple: update flatpak stable PPA during 10 years, for each LTS branch, up to the end of Ubuntu Pro support.

This is unlikely to happen unless an Ubuntu developer volunteers to make it happen, or someone pays for developers to do this as part of their jobs. The maintainers of the PPA have too many other responsibilities and not enough spare time to keep updating backported packages free of charge for a decade, or to commit to any sort of service level agreement.
