### ISSUE TITLE
Builds for non-LTS branches not available in PPA

### ISSUE THREAD

**Issue by RogueScholar** [flatpak/ppa-flatpak#2]
When you have a moment, could you push a source package for Groovy to the PPA? The Canonical repos ship 1.8.2 still. Perhaps one for Hirsute as well, since it is also behind upstream and might help avoid playing catch-up with new releases going forward. Thanks so much!

**Comment by smcv** [comment]
Please use the newest available LTS suite (currently `focal`) for now. It should install OK on groovy and hirsute.

I don't think the PPA is going to get non-LTS suites any time soon: that would be a significant increase in the number of things to build and test, and the PPA maintainer doesn't even use Ubuntu.

**Comment by smcv** [comment]
groovy reached end-of-life a long time ago, but the situation for newer branches is similar: users of Ubuntu kinetic (22.10) will need to use the packages intended for jammy (22.04 LTS) if they want to use this PPA, and so on.

This is not going to change unless Ubuntu developers step up to do the work. I am not an Ubuntu developer or an Ubuntu user (I only run it on test machines for the benefit of Ubuntu users), so I don't really even have enough time available to keep this repository up-to-date for all the LTS branches of Ubuntu, never mind the non-LTS ones.
