### ISSUE TITLE
Please release 1.11.2

### ISSUE THREAD

**Issue by smcv** [flatpak/ppa-flatpak#4]
I've pushed updated packaging for 1.11.2 to the `ppa/focal`, `ppa/bionic` and `ppa/xenial` branches, but I'm not @alexlarsson, so I can't do the final uploads.

These packages have been resynced with official packages in Debian experimental, and now have a minimal amount of backporting: `ppa/focal` is relatively close to Debian, `ppa/bionic` has more backporting, and `ppa/xenial` has lots. This means the larger backport changes will automatically disappear when we stop caring about xenial.

**Comment by alexlarsson** [comment]
Building in the ppa now.
