### ISSUE TITLE
Signing key

### ISSUE THREAD

**Issue by concatime** [flatpak/ppa-flatpak#6]
Can you specify in the "Technical details about this PPA" which signing key you use?  All the PPA that I know do this. [Git](https://launchpad.net/~git-core/+archive/ubuntu/ppa) for example does this.
Thank you.

**Comment by smcv** [comment]
The signing key is managed by Launchpad, not directly by us, and we don't choose what its user interface in Launchpad looks like.

I don't know why the Git PPA shows a signing key under the "Technical details about this PPA" expander but ours doesn't. Please could you report this as a Launchpad issue?

**Comment by concatime** [comment]
If you have nothing to do with the fact that the signing key is not shown in the PPA, then there is no need for this issue. That being said, I’ve been using a dozen of PPAs, and this is the first time the signing key isn’t available. I thought the issue was on your side.

**Comment by smcv** [comment]
If there's a setting we can change to make the signing key more visible, I'm happy to change it, but someone who knows more about PPAs would have to tell me where. None of the configuration that I can see seems to be relevant.

**Comment by concatime** [comment]
Well, it seems the key is [0x5C6D153A17C02C337EF6C663B8B9D41229DFA5F5](https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x5C6D153A17C02C337EF6C663B8B9D41229DFA5F5).

**Comment by smcv** [comment]
I assume `apt-add-repository` must be using some sort of Launchpad API to find the right key, but I don't know what (I don't use Ubuntu myself).
